### ISSUE TITLE
David S. Pumpkins is getting old

### ISSUE THREAD

**Issue by eponvert** [tx10indivisible/tx10indivisible.github.io-v1#13]

**Comment by chip-rosenthal** [comment]
I think we should have some graphic in that page. It's linked and shared a lot, so whatever photo is there tends to get thumbnailed. I've got photos from in-person events that we can use. If somebody wants to take this, contact me.

Any questions?

**Comment by eponvert** [comment]
Sure send me some photos or link then here and I'll try it.

**Comment by amullins83** [comment]
@eponvert Did you get any images yet?

**Comment by eponvert** [comment]
I still need to
